### ISSUE TITLE
Slack notifications for manglende timeregistrering i slutten av uka

### ISSUE THREAD

**Issue by niclasalv** [Alv-no/alvtime-slack-app#5]

**Comment by Trulsaa** [comment]
TimeEntriesReport endepunktet returnerer Id til brukeren. Slack appen har ingen måte å vite hvilken bruker det nummeret koresponderer til uten å bruke ett adimin endepunkt i tillegg. Kan id byttes ut med email? Evt legge til email? @palbock90 @lnordhus @mskjonhaugalv

**Comment by palbock** [comment]
@Trulsaa Da er email lagt til
